package lab7p2_lloydcooperr;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author CUSTOMER PC
 */
public class frameMain extends javax.swing.JFrame {

    private ArrayList <Vendedor> vendedores = new ArrayList();
    private ArrayList <Cliente> clientes = new ArrayList();
    private ArrayList <Vehiculo> vehiculos = new ArrayList();
    private ArrayList <Venta> ventas = new ArrayList();
    
    public frameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupModificarArchivo = new javax.swing.JPopupMenu();
        menuItemModificar = new javax.swing.JMenuItem();
        dialogModificarArchivo = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        taListarArchivo = new javax.swing.JScrollPane();
        btnModificarArchivo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrearVendedor = new javax.swing.JButton();
        tfNombreVendedor = new javax.swing.JTextField();
        tfCantCarrosVendidos = new javax.swing.JTextField();
        tfCantDineroGenerado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNombreCliente = new javax.swing.JTextField();
        tfEdadCliente = new javax.swing.JTextField();
        tfProfesionCliente = new javax.swing.JTextField();
        tfCantCarrosComprados = new javax.swing.JTextField();
        tfSueldoDisponible = new javax.swing.JTextField();
        btnCrearCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfMarcaVehiculo = new javax.swing.JTextField();
        tfModeloVehiculo = new javax.swing.JTextField();
        tfPrecioVehiculo = new javax.swing.JTextField();
        ycAño = new com.toedter.calendar.JYearChooser();
        btnCrearVehiculo = new javax.swing.JButton();
        tfColorVehiculo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cbVendedor = new javax.swing.JComboBox<>();
        cbCliente = new javax.swing.JComboBox<>();
        cbVehiculo = new javax.swing.JComboBox<>();
        btnHacerVenta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeAdmin = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeDia = new javax.swing.JTree();
        btnUpdateDiaTree = new javax.swing.JButton();
        btnUpdateAdminTree = new javax.swing.JButton();
        btnFinalizarDia = new javax.swing.JButton();

        menuItemModificar.setText("Modificar archivo");
        menuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarActionPerformed(evt);
            }
        });
        popupModificarArchivo.add(menuItemModificar);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnModificarArchivo.setText("Modificar archivo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taListarArchivo)
                    .addComponent(btnModificarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(taListarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarArchivo)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogModificarArchivoLayout = new javax.swing.GroupLayout(dialogModificarArchivo.getContentPane());
        dialogModificarArchivo.getContentPane().setLayout(dialogModificarArchivoLayout);
        dialogModificarArchivoLayout.setHorizontalGroup(
            dialogModificarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogModificarArchivoLayout.setVerticalGroup(
            dialogModificarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de carros vendidos");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad de dinero generado");

        btnCrearVendedor.setText("Crear vendedor");
        btnCrearVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearVendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfCantDineroGenerado))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCantCarrosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCantCarrosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCantDineroGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear vendedor", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Profesion");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad de carros comprados");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sueldo disponible");

        btnCrearCliente.setText("Crear cliente");
        btnCrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(80, 80, 80)
                            .addComponent(tfSueldoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfCantCarrosComprados))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(122, 122, 122)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNombreCliente)
                                .addComponent(tfEdadCliente)
                                .addComponent(tfProfesionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                    .addComponent(btnCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfProfesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfCantCarrosComprados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfSueldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear cliente", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Marca");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Color");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Modelo");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Año");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Precio");

        btnCrearVehiculo.setText("Crear vehiculo");
        btnCrearVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearVehiculoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMarcaVehiculo)
                            .addComponent(tfModeloVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tfPrecioVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(ycAño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfColorVehiculo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tfModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfPrecioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ycAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear vehiculo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnHacerVenta.setText("Hacer venta");
        btnHacerVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerVentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHacerVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHacerVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venta", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Admin");
        treeAdmin.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeAdmin);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dia");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Venta");
        treeNode1.add(treeNode2);
        treeDia.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeDiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(treeDia);

        btnUpdateDiaTree.setText("Update day tree");

        btnUpdateAdminTree.setText("Update admin tree");

        btnFinalizarDia.setText("Finalizar dia");
        btnFinalizarDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinalizarDia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinalizarDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarDiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateAdminTree, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btnUpdateDiaTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateDiaTree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateAdminTree))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trees", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearVendedorMouseClicked
        String nombreVendedor = tfNombreVendedor.getText();
        int cantCarrosVendidos = 0;
        int cantDineroGenerado = 0;

        try {
            cantCarrosVendidos = Integer.parseInt(tfCantCarrosVendidos.getText());
            cantDineroGenerado = Integer.parseInt(tfCantDineroGenerado.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (tfNombreVendedor.getText().isEmpty() || tfCantCarrosVendidos.getText().isEmpty() || tfCantDineroGenerado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Debe llenar todos los campos");
        } else {
            vendedores.add(new Vendedor(nombreVendedor, cantCarrosVendidos, cantDineroGenerado));
            cbVendedor.setModel(updateComboBoxVendedores());
            JOptionPane.showMessageDialog(this,"Vendedor creado correctamente");
            generarJsonFileVendedor(vendedores);
        }

        tfNombreVendedor.setText("");
        tfCantCarrosVendidos.setText("");
        tfCantDineroGenerado.setText("");
    }//GEN-LAST:event_btnCrearVendedorMouseClicked

    private void btnCrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearClienteMouseClicked
        String nombreCliente = tfNombreCliente.getText();
        int edadCliente = 0;
        String profesionCliente = tfProfesionCliente.getText();
        int cantCarrosComprados = 0;
        int sueldoDisponible = 0;
        
        try {
            edadCliente = Integer.parseInt(tfEdadCliente.getText());
            cantCarrosComprados = Integer.parseInt(tfCantCarrosComprados.getText());
            sueldoDisponible = Integer.parseInt(tfSueldoDisponible.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numericos validos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        if (tfNombreCliente.getText().isEmpty() || tfEdadCliente.getText().isEmpty() || tfProfesionCliente.getText().isEmpty()
            || tfCantCarrosComprados.getText().isEmpty() || tfSueldoDisponible.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
        } else {
            clientes.add(new Cliente(nombreCliente, edadCliente, profesionCliente, cantCarrosComprados, sueldoDisponible));
            cbCliente.setModel(updateComboBoxClientes());
            JOptionPane.showMessageDialog(this, "Cliente creado correctamente");
            generarJsonFileClientes(clientes);
        }
        
        clientes.add(new Cliente(nombreCliente, edadCliente, profesionCliente, cantCarrosComprados, sueldoDisponible));
        
        tfNombreCliente.setText("");
        tfEdadCliente.setText("");
        tfProfesionCliente.setText("");
        tfCantCarrosComprados.setText("");
        tfSueldoDisponible.setText("");
    }//GEN-LAST:event_btnCrearClienteMouseClicked

    private void btnCrearVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearVehiculoMouseClicked
        String marcaVehiculo = tfMarcaVehiculo.getText();
        String colorVehiculo = tfColorVehiculo.getText();
        String modeloVehiculo = tfModeloVehiculo.getText();
        String año = String.valueOf(ycAño.getY());
        int precioVenta = 0;
        
        try {
            precioVenta = Integer.parseInt(tfPrecioVehiculo.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numericos validos.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
       
        if (tfMarcaVehiculo.getText().isEmpty() || tfModeloVehiculo.getText().isEmpty() || tfPrecioVehiculo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
        } else {
            vehiculos.add(new Vehiculo(marcaVehiculo, colorVehiculo, modeloVehiculo, año, precioVenta));
            cbVehiculo.setModel(updateComboBoxVehiculos());
            JOptionPane.showMessageDialog(this,"Vehiculo creado correctamente");
            generarJsonFileVehiculos(vehiculos);
        }

        tfMarcaVehiculo.setText("");
        tfColorVehiculo.setText("");
        tfModeloVehiculo.setText("");
        tfPrecioVehiculo.setText("");
    }//GEN-LAST:event_btnCrearVehiculoMouseClicked
    int idCarro = 0;
    private void btnHacerVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerVentaMouseClicked
        if (cbVendedor.getSelectedIndex() >= 0 || cbCliente.getSelectedIndex() >= 0 || cbVehiculo.getSelectedIndex() >= 0) {
            Vendedor vendedor = vendedores.get(cbVendedor.getSelectedIndex());
            Cliente cliente = clientes.get(cbCliente.getSelectedIndex());
            Vehiculo vehiculo = vehiculos.get(cbVehiculo.getSelectedIndex());
            String clients = cliente.getNombreCliente();
            String sellers = vendedor.getNombreVendedor();
            int costo = vehiculo.getPrecioVenta();
            String marca = vehiculo.getMarcaVehiculo();
            
            ventas.add(new Venta(sellers, clients, costo, clients, idCarro));
            JOptionPane.showMessageDialog(this, "Venta realizada correctamente");
            File file = null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                file = new File("src/ventas.txt");
                fw = new FileWriter(file,true);
                bw = new BufferedWriter(fw);
                
                String jsonVentas = "[\n"
                                    + "\t" + sellers + "\n"
                                    + "\t" + clients + "\n"
                                    + "\t" + costo + "\n"
                                    + "\t" + marca + "\n]\n" ;
                
                bw.write(jsonVentas);
                bw.flush();
                fw.close();
                bw.close();
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_btnHacerVentaMouseClicked

    private void treeDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeDiaMouseClicked
        if (evt.isMetaDown()) {
            popupModificarArchivo.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_treeDiaMouseClicked

    private void menuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarActionPerformed
        dialogModificarArchivo.pack();
        dialogModificarArchivo.setModal(true);
        dialogModificarArchivo.setLocationRelativeTo(this);
        dialogModificarArchivo.setVisible(true);
    }//GEN-LAST:event_menuItemModificarActionPerformed

    private void btnFinalizarDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarDiaMouseClicked
        int confirmar = JOptionPane.showConfirmDialog(this, "Desea confirmar?", "Confirmar", ConfirmationCallback.YES_NO_CANCEL_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            String path = "src/";
            File file = null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            String line = "";
            path += JOptionPane.showInputDialog("Ingrese el nombre del archivo de actividad");
            path += ".txt";
            
            try {
                file = new File(path);
                fw = new FileWriter(file, true);
                bw = new BufferedWriter(fw);
                int contador = 1;
                for (Venta venta : ventas) {
                    line = "[\n"
                           + "\t" + contador + "\n"
                           + "\t" + venta.getCliente() + "\n"
                           + "\t" + venta.getVendedor() + "\n"
                           + "\t" + venta.getCarroVendido() + "\n"
                           + "\t" + venta.getIdCarro() + "\n]\n" ;
                    bw.write(line);
                    contador++;
                }
                bw.flush();
                fw.close();
                bw.close();
                ventas.clear();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnFinalizarDiaMouseClicked

    private void generarJsonFileVendedor(ArrayList vendedores) {
        StringBuilder archivoJson = new StringBuilder();

        for (int i = 0; i < vendedores.size(); i++) {
            Vendedor vendedor = (Vendedor) vendedores.get(i);

            archivoJson.append("[").append("\n");
            
            archivoJson.append("\t").append(vendedor.getNombreVendedor()).append("\n");
            archivoJson.append("\t").append(vendedor.getCantCarrosVendidos()).append("\n");
            archivoJson.append("\t").append(vendedor.getCantDineroGenerado()).append("\n");

            archivoJson.append("]").append("\n");
        }


        String filePath = "src/vendedores.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(archivoJson.toString());
            writer.close();
            JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generarJsonFileClientes(ArrayList clientes) {
        StringBuilder archivoJson = new StringBuilder();
        archivoJson.append("[\n");

        for (int i = 0; i < clientes.size(); i++) {
            Cliente cliente = (Cliente) clientes.get(i);

            if (i > 0) {
                archivoJson.append(",\n");
            }
            archivoJson.append("[").append("\n");
            
            archivoJson.append("\t").append(cliente.getNombreCliente()).append(",\n");
            archivoJson.append("\t").append(cliente.getEdadCliente()).append(",\n");
            archivoJson.append("\t").append(cliente.getProfesionCliente()).append("\n");
            archivoJson.append("\t").append(cliente.getCantCarrosComprados()).append("\n");
            archivoJson.append("\t").append((char) cliente.getSueldoDisponible()).append("\n");
            
            archivoJson.append("[").append("\n");
        }

        archivoJson.append("\n]");

        String filePath = "src/clientes.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(archivoJson.toString());
            writer.close();
            JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void generarJsonFileVehiculos(ArrayList vehiculos) {
        StringBuilder archivoJson = new StringBuilder();
        archivoJson.append("[\n");

        for (int i = 0; i < vehiculos.size(); i++) {
            Vehiculo vehiculo = (Vehiculo) vehiculos.get(i);

            if (i > 0) {
                archivoJson.append(",\n");
            }
            archivoJson.append("[").append("\n");
            
            archivoJson.append("\t").append(vehiculo.getMarcaVehiculo()).append(",\n");
            archivoJson.append("\t").append(vehiculo.getColorVehiculo()).append("\n");
            archivoJson.append("\t").append(vehiculo.getModelo()).append(",\n");
            archivoJson.append("\t").append(vehiculo.getAño()).append("\n");
            archivoJson.append("\t").append(vehiculo.getPrecioVenta()).append("\n");
            
            archivoJson.append("[").append("\n");
        }

        archivoJson.append("\n]");

        String filePath = "src/vehiculos.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(archivoJson.toString());
            writer.close();
            JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public DefaultComboBoxModel updateComboBoxVendedores(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Vendedor vendedor : vendedores) {
            modelo.addElement(vendedor);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel updateComboBoxClientes(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Cliente cliente : clientes) {
            modelo.addElement(cliente);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel updateComboBoxVehiculos(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Vehiculo vehiculo : vehiculos) {
            modelo.addElement(vehiculo);
        }
        return modelo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearVehiculo;
    private javax.swing.JButton btnCrearVendedor;
    private javax.swing.JButton btnFinalizarDia;
    private javax.swing.JButton btnHacerVenta;
    private javax.swing.JButton btnModificarArchivo;
    private javax.swing.JButton btnUpdateAdminTree;
    private javax.swing.JButton btnUpdateDiaTree;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JDialog dialogModificarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuItemModificar;
    private javax.swing.JPopupMenu popupModificarArchivo;
    private javax.swing.JScrollPane taListarArchivo;
    private javax.swing.JTextField tfCantCarrosComprados;
    private javax.swing.JTextField tfCantCarrosVendidos;
    private javax.swing.JTextField tfCantDineroGenerado;
    private javax.swing.JTextField tfColorVehiculo;
    private javax.swing.JTextField tfEdadCliente;
    private javax.swing.JTextField tfMarcaVehiculo;
    private javax.swing.JTextField tfModeloVehiculo;
    private javax.swing.JTextField tfNombreCliente;
    private javax.swing.JTextField tfNombreVendedor;
    private javax.swing.JTextField tfPrecioVehiculo;
    private javax.swing.JTextField tfProfesionCliente;
    private javax.swing.JTextField tfSueldoDisponible;
    private javax.swing.JTree treeAdmin;
    private javax.swing.JTree treeDia;
    private com.toedter.calendar.JYearChooser ycAño;
    // End of variables declaration//GEN-END:variables
}
